### ISSUE TITLE
bootloader compile conflict with esp-idf

### ISSUE THREAD

**Issue by nubcore** [micropython/micropython-esp32#13]
There's an issue trying to compile against the current version of the esp-idf relating to changes in the bootloader.

I was able to work around this by checking out a older version of esp-idf.

<pre>/espidf: git checkout 0efaa4f4b817c7b056108bcd0c6233ed6589bc49</pre>

thx to projectgus for the suggestion

**Comment by nickzoic** [comment]
Hey there nubcore!  Thanks for letting us know, this is unfortunately a chronic problem with esp-idf for all the projects which are using it ... it is currently a moving target.

Because micropython builds all sorts of other platforms too it isn't really appropriate to pull esp-idf in as a submodule, but if you look at the esp32/Makefile there's an 'idf-version' target which prints the (hopefully) correct esp-idf version for building against ...

I think it might be a good idea if we work out a way to actually check this version as part of the build process because it's bitten me a few times too!

**Comment by nubcore** [comment]
ah, the idf-version is exactly what I was looking for just didn't know it. correction to my note above, the version I was looking for is actually...

`make idf-version`
`IDF version: bf3093feca1f470bdd6caf45adf3b71492b84a19`

should this issue be closed, or left open for future enhancement?

**Comment by dpgeorge** [comment]
I made updates to compile with the latest ESP IDF, see e9e89b4beb77ea52882708667ce8dbab37f86848

> I think it might be a good idea if we work out a way to actually check this version as part of the build process because it's bitten me a few times too!

Would be good.  But hopefully the IDF matures in the future so such a check is not needed.

**Comment by MartyMacGyver** [comment]
I'm curious - have you seen this error? If not, maybe it's something weird on my end:

    /esp-idf/components/bootloader/src/main/bootloader_start.c:245:54: error: 'IDF_VER' undeclared (first use in this function)

**Comment by dpgeorge** [comment]
> have you seen this error? If not, maybe it's something weird on my end:

Yes, that will happen with the very latest IDF.  Please use the version of the IDF as described by `make idf-version` run from within the esp32 dir of this repo (the ESP IDF has been changing *very* quickly over the past weeks).

**Comment by MartyMacGyver** [comment]
I thought I was. It looked to have the same version when I checked it.

I'm a bit confused... you made updates to support the latest IDF but that IDF version isn't the latest?

**Comment by nickzoic** [comment]
I think it changed again in the meantime.  This thing moves at a gallop,
with new branches getting merged in all the time.


So your best bet is to 'make idf-version' in the micropython-esp32/esp32
directory, which will give you a version of the IDF which micropython
has actually been built against,  then go into esp-idf and 'git checkout
$THAT_VERSION', then back across to micropython to build.


At some point we'll want to automate this, but it isn't there
just yet ...


-----N





On Fri, Jan 13, 2017, at 15:23, Martin Falatic wrote:

> I thought I was. It looked to have the same version when I checked it.
> I'm a bit confused... you made updates to support the latest IDF but
> that IDF version isn't the latest?
--

Nick Moore <nick@zoic.org> 0409 656 267

**Comment by dpgeorge** [comment]
> I'm a bit confused... you made updates to support the latest IDF but that IDF version isn't the latest?

The update to the latest version was made 24 hours ago, but since then there have been 74 commits to ESP IDF...

In 864d52764a247d9f9785614a667298dd91bfd2f3 I added a check for the ESP git hash, and a warning will be printed if it's not the supported version (but the build will still be attempted).

**Comment by MartyMacGyver** [comment]
I think in all the updating today my data was incorrect. I had that specific hash earlier, which matched your IDF... but I hadn't updated the idf in a couple of days. Long story short, now I see what you mean.

Bonus - I think I unblocked that error as well. If it works (I'm actually going to completely clean build this and try it again) I can submit the Makefile update as a pull request.

**Comment by MartyMacGyver** [comment]
Thanks again - I reverted the esp-idf (and its submodules) to the 864d527 environment and rebuild and flashed successfully (`FLASH_MODE=dio` was necessary).

I'm not sure how you'll integrate the more recent esp-idf changes but FWIW I was also able to make this build and flash against the latest code, though it didn't end up working on the target.

In `esp32/Makefile`, I made a couple of changes to get this done (these changes are also backward compatible with the old esp-idf environment since it ignores IDF_VER):

- Early in the makefile, `IDF_VER := $(shell git -C $(IDF_PATH) describe)`
- CFLAGS and CXXFLAGS need `-D IDF_VER=\"$(IDF_VER)\"` added

**Comment by dpgeorge** [comment]
In 9f2aeedce9a781758ac82e957461c42be9504829 I updated to the latest ESP IDF, which includes the `IDF_VER` change, as well as some other things.

**Comment by MartyMacGyver** [comment]
It works!

I'm using slightly streamlined build steps (less chdir-ing and more (optional) pre-cleaning), custom port, and `dio` since in Windows that's the only mode that seems to work right when flashing:

    # Open a command prompt / MSYS2 prompt, then:
    export IDF_PATH=/c/esp-idf   # Full path, Unix style even on Windows
    export ESPIDF=$IDF_PATH
    export PORT=COM17
    git clone https://github.com/micropython/micropython-esp32  # If initializing
    cd micropython-esp32/esp32
    make -C ../mpy-cross clean  # Optional
    make -C ../mpy-cross
    make clean  # Optional
    make
    make PORT=$PORT FLASH_MODE=dio erase  # Optional?
    make PORT=$PORT FLASH_MODE=dio deploy

**Comment by dpgeorge** [comment]
@MartyMacGyver that's good news!  As suggested in the esp32/README.md, you can create a file called "makefile" which should override the "Makefile" and then you can set your config options in there (like PORT), instead of exporting them all the time, or passing them explicitly to make.  (This works on Linux and may work on Windows if you have the right version/brand of make.)

The "make erase" is only needed if you had something other than MicroPython on the chip.

**Comment by MartyMacGyver** [comment]
On Windows (and even a Mac with the default case-insensitive filesystem) `makefile` would clobber `Makefile`... that's why I went with the more portable inline solution.

**Comment by dpgeorge** [comment]
> On Windows (and even a Mac with the default case-insensitive filesystem) makefile would clobber Makefile

You could try `GNUmakefile`

**Comment by MartyMacGyver** [comment]
True, that would work.

That said, I still wouldn't suggest a user create a makefile when simple commands would suffice. Makefiles are not exactly user-friendly, and you still end up making some kind of wrapper script with similar steps if you're automating the process steps.

If PORT and FLASH_MODE (as used in the makefiles) took hints from certain environment variables (when present) this would be dirt-simple: set a few env vars (e.g., in `.profile`) and run standard unadorned commands.

That all said, I submit my suggestions as a small streamlining of the current process, and as informative for those who don't want to deal with making more makefiles (or who wish to wrap the whole thing in automation).

**Comment by MartyMacGyver** [comment]
And one last thing: `thank you!` for the hard work you and the others have put into bringing MicroPython to the ESP32. :-)

**Comment by dpgeorge** [comment]
> If PORT and FLASH_MODE (as used in the makefiles) took hints from certain environment variables (when present) this would be dirt-simple: set a few env vars (e.g., in .profile) and run standard unadorned commands.

It already works that way (at least on Linux): `export PORT=blah` will override the one in Makefile.  Personally, I don't like to litter my shell with env variables, so I use makefile.

> And one last thing: thank you! for the hard work you and the others have put into bringing MicroPython to the ESP32. :-)

My pleasure!  But moving forward, I hope this port gains contributions from the community so it can grow with a purpose.
