### ISSUE TITLE
UART.writechar() implementation / UART.write single byte behavior

### ISSUE THREAD

**Issue by 0xDBFB7** [micropython/micropython-esp32#174]
Since there's no UART.writechar() implementation, it is currently impossible to use protocols like Xmodem, insofar as I can see.

---

I'm pretty sure this is expected behavior,

If I do this:

`sam_uart.write('\x7f')`

or this:

`sam_uart.write(chr(127))`

And then check the output on a hex viewer, I get 

`0x7f`

Which is correct. If I do this:

`sam_uart.write(chr(128))`

or this:

`sam_uart.write('\x80')`

I get 

> 0xc2 0x80

If I do this:

`sam_uart.write(chr(255))`

I get 

> 0xC3 0xBF

However, on an Arduino, this isn't the behavior - Serial.write, when given one byte, writes that byte verbatim.

Had me tearing my hair out.

**Comment by MrSurly** [comment]
It's sending the UTF8 encoding. What happens when you use a 'bytearray'?

write(b'\x80')



On Sep 1, 2017 13:40, "Daniel Correia" <notifications@github.com> wrote:

Since there's no UART.writechar() implementation, it is currently
impossible to use protocols like Xmodem.

--
I'm pretty sure this is expected behavior,

If I do this:

sam_uart.write('\x7f')

or this:

sam_uart.write(chr(127))

And then check the output on a hex viewer, I get

0x7f

Which is correct. If I do this:

sam_uart.write(chr(128))

or this:

sam_uart.write('\x80')

I get

0xc2 0x80

If I do this:

sam_uart.write(chr(255))

I get

0xC3 0xBF

However, on an Arduino, this isn't the behavior - Serial.write, when given
one byte, writes that byte verbatim.

Had me tearing my hair out.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/micropython/micropython-esp32/issues/174>, or mute the
thread

**Comment by 0xDBFB7** [comment]
@MrSurly That works! However, bytearray doesn't work - it has the same problem.

**Comment by MrSurly** [comment]
I'm confused, did it work, or didn't it?

**Comment by 0xDBFB7** [comment]
@MrSurly Sorry, b'\x80' works, but bytearray('\x80') doesn't.

**Comment by 0xDBFB7** [comment]
@MrSurly For the record, bytes([0x80]) worked. Thanks for your help.

**Comment by dpgeorge** [comment]
> but bytearray('\x80') doesn't.

That's because that piece of code converts the string "\x80" to a utf8 encoded byte stream.  You can use `bytearray([0x80])` or `bytearray(b'\x80')`, but the most efficient thing is `b'\x80'`.

**Comment by 0xDBFB7** [comment]
@dpgeorge Yup, serves me right to not learn the workings of python 3 strings before raising an issue :)

**Comment by nickzoic** [comment]
I'd argue this is a bug in MicroPython, because bytearray('\x80') should
throw a TypeError in Python3.
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23)

>>> bytearray([0x80])
bytearray(b'\x80')

>>> bytearray(b'\x80')
bytearray(b'\x80')

>>> bytearray('\x80')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string argument without an encoding

>>> bytearray('\x80', 'utf-8')
bytearray(b'\xc2\x80')
```

... throwing these exceptions is annoying, but less annoying than not
throwing them!

**Comment by dpgeorge** [comment]
> I'd argue this is a bug in MicroPython, because bytearray('\x80') should throw a TypeError in Python3.

Yes good point.
