### ISSUE TITLE
GURU: LoadProhibited crash with socket when no bind address

### ISSUE THREAD

**Issue by pacmac** [micropython/micropython-esp32#31]
A minor issue I know, but I thought I would report it:

This causes crash:

    import socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(('',80))

This does not:

    import socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(('0.0.0.0',80))

**Comment by nickzoic** [comment]
OK, thanks for reporting it because that's how we find stuff!

This is missing error handling in my code: `""` isn't a valid address for `lwip_getaddrinfo` so it is returning an error code which modsocket is ignoring, leading to the usual C chaos.

Interestingly, Python2/3 on Linux anyway seems to special-case strings which might be IP addresses, eg: `""`, `"0"`, `"00000"`, `"0.0.0"` (but not `"0.0.0.0.0"`) ... so that's interesting and maybe we should be doing that as well :-).

**Comment by nickzoic** [comment]
The "" case is covered by 1365f7f29 ... and no-one's complained about the others so I'm going to close this one off.
