### ISSUE TITLE
GUI tool to upload the Micropython firmware of ESP-32

### ISSUE THREAD

**Issue by neoxharsh** [micropython/micropython-esp32#38]
I have made an easy to use tool to upload the Micropython firmware to ESP32, and also provided a compiled version of Micropython for ESP32 

[ESP GUI Flasher](https://github.com/neoxharsh/ESP32-GUI-Flasher)

**Comment by nickzoic** [comment]
This is quite a cool idea, since there's lots of Windows / Mac people who don't really know what a terminal is ... a simplified loading experience would be nice.  I'll definitely check it out and send some comments.

But it isn't a bug or feature request on the MicroPython port, so I'm closing it here ...

**Comment by dpgeorge** [comment]
If you'd like to advertise this, please use https://forum.micropython.org
