### ISSUE TITLE
orphan link to urequests.py

### ISSUE THREAD

**Issue by pacmac** [micropython/micropython-esp32#51]
I just noticed in the esp32/modules folder, an orphaned symbolic link:

    urequests.py -> ../../../micropython-lib/urequests/urequests.py

This path does not appear to exist:

    >>> import urequests
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
    ImportError: no module named 'urequests'
    >>>

**Comment by dpgeorge** [comment]
That link is intentional.  The idea is that you have the micropython-lib repository cloned and available at that path.  Then it will include the urequests module (and possibly others in the future) in the build.  If the path doesn't exist then it does no harm, the symlink is not followed and nothing is included.
